### ISSUE TITLE
Rematch

### ISSUE THREAD

**Issue by amosshahor** [ysnappir/hanabi#68]
When the game is over, either won or lost, propose a rematch in a popup.
In the popup, you should have a list of all players, and every player that pressed will be marked, say by a green background/frame.

If there are at least two marked players, they can click the "start" button.

If you want to be a pro - add a countdown and at the end of it, start the game with the marked players (if there are at least two participants).

**Comment by ysnappir** [comment]
Currently there is a button to rematch for all.
Closing this and will add features regarding https://github.com/ysnappir/hanabi/issues/71

**Comment by amosshahor** [comment]
When there's a rematch, does it keep the order of the players?
Is the starting player of the new game the one after who started the current one?
