### ISSUE TITLE
Unflipping a card

### ISSUE THREAD

**Issue by amosshahor** [ysnappir/hanabi#74]
Allow the user to undo a card flip by double-clicking it.
It should be possible only until the next turn was played.
It should unflip it and bring the deck to the state before it was moved (including the hint marking).

To alternatives that will be easier to implement - 
- Double click on any flipped card brings the state to the way it was before this turn.
- Only allow to undo the last flipped card, not all cards that were flipped in this turn.

**Comment by ysnappir** [comment]
You are mixing to independent things: turns and card motions.
Card motions are allowed at all times if they comply with the rules and they are strictly decoupled from turns.

You might say that an unflip can occur until player's hand changes. How about that?

**Comment by amosshahor** [comment]
I'm not sure I follow
Let's discuss "F2F" tomorrow

**Comment by ysnappir** [comment]
Done!
